from schoolpro_database import save_student
import sqlite3
# SchoolPro Ghana 
# School Management Software 
# Developer: Issahak Abdul Halim(Hafiz)
# Version: 1.0

while True:
    print("===================================")
    print("Welcome to SchoolPro Ghana!")
    print("School Management Software")
    print("===================================")
    print("1. Student Registration")
    print("2. Attendance")
    print("3. Grades & Results")
    print("4. Fee Management")
    print("5. Teachers/Staff Management")
    print("6. View All Student")
    print("7. Exit")
    print("====================================")

    choice = input("Enter your choice (1-7): ")
    if choice =="1":
        print("================================")
        print("     Student REGISTRATION")
        print("================================")
        name = input("Enter student name: ")
        age = input("Enter student age: ")
        class_name = input("Enter class: ")
        section = input("Enter section (Academic/Islamic): ")
        print("================================")
        print("Student Registered Successfully!")
        print("Name: " + name)
        print("Age: " + age)
        print("Class: " + class_name)
        print("section: " + section)
        print("================================")
        save_student(name, age, class_name, section)
    elif choice == "2":
        print("================================")
        print("        Attendance")
        print("================================")
        name = input("Enter student name: ")
        date = input("Enter date: ")
        status = input("Enter status (Present/Absent): ")
        print("================================")
        print("Attendance Recorded Successfully!")
        print("Student: " + name)
        print("Date: " + date)
        print("Status: " + status)
        print("================================")
    elif choice == "3":
        print("================================")
        print("        GRADES & RESULTS")
        print("================================")
        name = input("Enter student name: ")
        subject = input("Enter subject: ")
        score = input("Enter score: ")
        grade = input("Enter grade (A/B/C/D/F): ")
        print("================================")
        print("Grades Recorded Successfully!")
        print("Student: " + name)
        print("Subject: " + subject)
        print("Score: " + score)
        print("Grade: " + grade)
        print("================================")
    elif choice =="4":
        print("================================")
        print("       FEE MANAGEMENT")
        print("================================")
        name = input("Enter student name: ")
        amount = input("Enter amount paid (GHS): ")
        date = input("Enter date of payment: ")
        print("================================")
        print("Fee Recorded Successfully!")
        print("Student: " + name)
        print("Amount Paid: GHS" + amount)
        print("Date: " + date)
        print("================================")
    elif choice == "5":
        print("===========================================")
        print("        TEACHER/STAFF MANAGEMENT")
        print("===========================================") 
        name = input("Entert teacher name: ")
        subject= input("Enter subject: ")
        class_name = input("Enter class: ")
        phone = input("Enter phone number: ")
        section = input("Enter section (Academic/Islamic): ")
        print("============================================")
        print("Teacher Registration Successfully!")
        print("Name: " + name)
        print("Subject: " + subject)
        print("section: " + section)
        print("============================================")       
    elif choice == "6":
        print("================================")
        print("        ALL STUDENT")
        print("================================")
        conn = sqlite3.connect(' schoolpro.db')
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM students")
        students = cursor.fetchall()
        conn.close()
        if len(students) == 0:
            print("No students Registerd yet!")
        else:
            for student in students:
                print("ID: " + str(student[0]))
                print("Name: " + student[1])
                print("Age: " + student[2])
                print("Class: " + student[3])
                print("Section: " + student[4])
                print("----------------")
        print("================================")

    elif choice == "7":
        print("Goodbye! Thank you for using ShcoolPro Ghana!")
        break
    else:
        print("invalid choise! Please enter 1-5")
                       